### ISSUE TITLE
ICSD compounds returning 'icsd_id' : None

### ISSUE THREAD

**Issue by CJBartel** [materialsproject/mapidoc#12]
For example, see mp-30158 (Sr3Ga4O9), which appears to have an ICSD number of 51546 according to https://materialsproject.org/materials/mp-30158/. However, the result of a query using the API returns:
"{'icsd_id': None, 'material_id': 'mp-30158', 'pretty_formula': 'Sr3Ga4O9'}". 

Another example is mp-1098 (Yb4As3) which shows ICSD IDs 153671 42685 611589 on the site but returns:
"{'icsd_id': None, 'material_id': 'mp-1098', 'pretty_formula': 'Yb4As3'}" when queried.

**Comment by shyamd** [comment]
@CJBartel 
At some point icsd_id was deprecated in our data pipeline in favor of icsd_ids, which should have all the relevant ICSD IDs.

**Comment by CJBartel** [comment]
Ah I see. Makes sense. Thanks for responding so quickly.

**Comment by dwinston** [comment]
I've updated our [site documentation](https://materialsproject.org/docs/api) to reflect this. Thanks.

**Comment by shyuep** [comment]
@dwinston You should also modify the mapidoc.

**Comment by jmm10** [comment]
Is there a way to only get the structure's actual ICSD number?

**Comment by shyuep** [comment]
Query for "icsd_ids"

**Comment by jmm10** [comment]
I did, but I get the ICSD numbers of those that are "structurally similar" to the material I look for; is there a way to only get the actual ICSD?
For example:
-material id=mp-20305
-actual ICSD number is 24518
However,  "icsd_ids" returns all of the following:
[610682 610687 610699 43974 43360 610683 610697 610694 190415 184924 185083 610689 44845 610686 610700 24518 610684 610698 181197 610685 165462 600849 610695 610701 41444]
Thank you for your help
