### ISSUE TITLE
why are pymatgen examples in this repo?

### ISSUE THREAD

**Issue by computron** [materialsproject/mapidoc#17]
I searched for "phonon" because I wanted to see if MAPI had a way for me to get the phonon information

I didn't find it, but the repo has a notebook about plotting phonon band structure that has nothing to do with materials API. There seem to be many pymatgen examples that don't involve MAPI at all that are in this repo. Not sure why? Pymatgen has its own page dedicated to pymatgen examples: https://matgenb.materialsvirtuallab.org

**Comment by shyuep** [comment]
I fixed this. But just a note that pymatgen does contain endpoints for the phonons. The puzzle is why these are not part of the REST API. @dwinston Can you either fix it or make sure it is documented here.

**Comment by dwinston** [comment]
Sure. The migration of the wiki docs to [markdown](http://docs.materialsproject.org/) should be completed soon, and with it will be an update/revamp of the listing of API endpoints. This repo is primarily for help with one endpoint, `/rest/v2/query`, and this will be clarified.
