### ISSUE TITLE
Experimentally realized materials

### ISSUE THREAD

**Issue by jonas-bjork** [materialsproject/mapidoc#18]
Hi!

Is there any information in the database whether a particular material has been experimentally realized or not?

Best wishes,
Jonas

**Comment by shyuep** [comment]
Technically no. But one way to "guess" is to check whether a material has an icsd_id. If there is, the likelihood is that it has been synthesized before, though ICSD also has purely computed structures too.

**Comment by mkhorton** [comment]
We are looking to add this flag in the near future, but there will always be a certain amount of false positives/false negatives.
