### ISSUE TITLE
How can I  obtain a mass of mp-id's property through  ”MPRester()“or ”requsets()“ more quickly?

### ISSUE THREAD

**Issue by wangyu-sd** [materialsproject/mapidoc#25]
Dear
I have a list of mp_id which is named as mp_list and is about 40k entries.  The code can be formulated as:
```
for i, mp_id in enumerate(tqdm(mp_list)):
  With open MPRester(API_KEY) as m:
    crystal_info = m.get_doc(mp_id) 
```
It did work and took about few hours, last month. But when I retried yesterday, it no longer worked, and would take me a about 300+ hours. Besides, when the progress bar reached about 2k/40k, the request was denied. So, I think whether  any error ocurred  when I need to obtain a large batch of mp_id's data using the code? This problem has been bothering me for days. I would be appreciated if you can give me some advice about it.

**Comment by shyuep** [comment]
This is a question to be posed to the Materials Project feedback team as it concerns their servers. Pls send your question to feedback@materialsproject.org.

**Comment by mkhorton** [comment]
Or, preferred, our public discussion @ [matsci.org/materials-project](matsci.org/materials-project) Thanks!
