### ISSUE TITLE
Retrieving only entries that match experimentally-determined crystal structure.

### ISSUE THREAD

**Issue by fedeotto** [materialsproject/mapidoc#26]
Hello,

I'm trying to find in the documentation a way to query all entries that match experimentally-determined crystal structure. I'm interested in band gap and formation energy, and made a query like this:

```
with MPRester("api_key") as mpr:
    
    entries= mpr.query(criteria = {"band_gap" : {"$gt":0.5}}, properties = ["band_gap", "formation_energy_per_atom"])
```

Is it possible to add something in the above code to fulfil my request?

Many thanks

**Comment by tschaume** [comment]
Please search the [MP forum ](https://matsci.org/c/materials-project/8) or post your question there if it hasn't been asked before. Thanks!
