### ISSUE TITLE
receiving no data for "input.parameters"

### ISSUE THREAD

**Issue by ZiqiGuo98** [materialsproject/mapidoc#27]
I am trying to check whether the data for the material is based on GW calculation. I found that it is under `input.parameters.MODEL_GW`.  But when I request `"input.parameters"`, there seems to be no data for all material. 
`data = m.query(criteria={
    "input.parameters":{"$exists":True}, 
                  }, 
            properties=["pretty_formula","input.parameters"])`
`Output: []`

I am wondering whether I made some mistake or there is really no data for `"input.parameters"`. 
Besides, is there any other way to know whether the material's data is based on GW calculation?
Thanks!

**Comment by tschaume** [comment]
Please search the [MP forum ](https://matsci.org/c/materials-project/8) or post your question there if it hasn't been asked before. Thanks!
