### ISSUE TITLE
put example YAML files of materials somewhere where people will find them

### ISSUE THREAD

**Issue by computron** [materialsproject/mapidoc#6]
right now it is in dev_scripts. These YAML files are very helpful when used in combination with the README descriptions. Indeed it would be nice if the READMEs were initialized using the YAML as example outputs.

**Comment by shyuep** [comment]
Erm, the READMEs are in fact initialized from the YAML. What do you mean by initialized? You mean actually putting in values?

**Comment by shyuep** [comment]
I just pushed an update that does this. Check out all the examples...
