### ISSUE TITLE
Manual specification of INCAR tags by user.

### ISSUE THREAD

**Issue by georgeyumnam** [materialsproject/mapidoc#9]
Can we have a cell in which the INCAR tags of the calculations are specified by the user.

I have recently come to find out that the fireworks which are getting cancelled (fizzled) are due to automatic consideration of the tetrahedron method (ISMEAR=-5) in the MP calculations. In order to avoid this, is there a way to manually specify the calculations and parameters for a particular submission?

Thanks!

**Comment by shyuep** [comment]
I am not sure what you mean here. You can always override any default parameters by supplying the "user_incar_settings" parameter to any input set you are using. Why is this a mapidoc issue?

**Comment by shyuep** [comment]
Also, if you use Custodian to do the runs, the ISMEAR error would be automatically dealt with.

**Comment by georgeyumnam** [comment]
I am sorry for the confusion here. My comment was on the provided example script:

mpcomplete_submit_structures_example.ipynb

 Thank you.

**Comment by shyuep** [comment]
@tschaume Pls comment. I would assume the MPComplete submissions should automatically be run via Custodian?

**Comment by tschaume** [comment]
Hi George,
Shyue is right that we'd indeed expect custodian to take care of changing the
ISMEAR parameter if the according error is triggered in the VASP calculation.
Can you send me a list of the fizzled FireWork IDs that you think should be
working with the parameter change? I'd need to take a look at the specific jobs
to see what happened.
thanks,Patrick

On Thu, Sep 29, 2016 8:37 AM, Shyue Ping Ong notifications@github.com
wrote:
Closed #9.

**Comment by georgeyumnam** [comment]
Hi Patrick,
Here are some fizzled Workflows: 1566137, 1566120, 1566104, 1566099, 1567504, 1567491. 

Here is the error as printed in the workflow details of one such case:
`{
"allow_zipped": false,
"filename": "FW_job.error",
"nlines": 25
},
-{
"allow_zipped": false,
"content": " old charge density:   184.00000 new  184.00479\n    0.105E+02\nRMM:  44    -0.633590437168E+02   -0.43602E+01   -0.17943E+00  2796   0.127E+00BRMIX: very serious problems\n the old and the new charge density differ\n old charge density:   184.00479 new  184.00000\n    0.108E+02\nRMM:  45    -0.634445412464E+02   -0.85498E-01   -0.14102E+00  2830   0.107E+00    0.108E+02\nRMM:  46    -0.643263321548E+02   -0.88179E+00   -0.14366E+00  2858   0.104E+00    0.108E+02\n  WARNING: DENTET: can't reach specified precision\n  Number of Electrons is NELECT =   184.040611693384\nRMM:  47    -0.659871266623E+02   -0.16608E+01   -0.16700E+00  2883   0.111E+00BRMIX: very serious problems\n the old and the new charge density differ\n old charge density:   184.00000 new  184.04062\n    0.109E+02\n  WARNING: DENTET: can't reach specified precision\n  Number of Electrons is NELECT =   183.983160084082\nRMM:  48    -0.599198525554E+02    0.60673E+01   -0.12354E+00  2663   0.102E+00BRMIX: very serious problems\n the old and the new charge density differ\n old charge density:   184.04062 new  183.98316\n    0.108E+02\nRMM:  49    -0.595777454523E+02    0.34211E+00   -0.12966E+00  2587   0.810E-01BRMIX: very serious problems\n the old and the new charge density differ\n old charge density:   183.98316 new  184.00000\n    0.107E+02\nRMM:  50    -0.658205142571E+02   -0.62428E+01   -0.14645E+00  2715   0.108E+00    0.110E+02",
"filename": "vasp.out",
"nlines": 25
}`

I have checked the error from the VASP user group for a similar error. Apparently, the solution to this problem was to either change the brillouin zone integration scheme or increase the grid/NEDOS of calculations. [http://cms.mpi.univie.ac.at/vasp-forum/viewtopic.php?t=416](url) 

Thank you.
George
